db:
  image: postgres:9.6
  environment:
    - POSTGRES_PASSWORD=spe1er
    - POSTGRES_USER=speler
    - POSTGRES_DB=musiek
  ports:
    - "5432:5432"
web:
  build: .
  volumes:
    - .:/code
    - /Users/jaco/Dropbox/music:/code/app/static/music
  links:
    - db
  ports:
    - "5656:5000"
  command: python run.py
