<?php

namespace JJ\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
    /**
     * Count all
     *
     * @return int
     */
    public function countAll()
    {
        $query = $this->getEntityManager()->createQuery("
                SELECT COUNT(b)
                FROM MainBundle:Album b
            ");
        return (int) $query->getSingleScalarResult();
    }

    /**
     * @param \DateTime $date
     * @return Album[]
     */
    public function findRemovable(\DateTime $date)
    {
        $query = $this->getEntityManager()->createQuery("
                SELECT b
                FROM MainBundle:Album b
                WHERE b.playedAt < :date
                ORDER BY b.playedAt ASC
            ")
            ->setParameters(array(
                'date' => $date
            ));
        return $query->getResult();
    }

    /**
     * @return Album[]
     */
    public function findIncomplete()
    {
        $query = $this->getEntityManager()->createQuery("
                SELECT b
                FROM MainBundle:Album b
                WHERE b.countSongs < b.size
            ");
        return $query->getResult();
    }
}
