<?php

namespace JJ\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends EntityRepository
{
    /**
     * Find last rated at
     *
     * @return \DateTime
     */
    public function findLastRatedAt()
    {
        $query = $this->getEntityManager()->createQuery("
                SELECT MIN(r.ratedAt)
                FROM MainBundle:Rating r
            ");
        $result = $query->getSingleScalarResult();
        return new \DateTime($result);
    }
}
