"""empty message

Revision ID: 1e825067143
Revises: 361392c4e67
Create Date: 2015-09-01 11:22:33.333014

"""

# revision identifiers, used by Alembic.
revision = '1e825067143'
down_revision = '361392c4e67'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('count_albums', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'count_albums')
    ### end Alembic commands ###
