"""empty message

Revision ID: 26044757012
Revises: 5282da66ae2
Create Date: 2015-08-21 14:43:05.115470

"""

# revision identifiers, used by Alembic.
revision = '26044757012'
down_revision = '5282da66ae2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('song', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'song', 'artist', ['artist_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'song', type_='foreignkey')
    op.drop_column('song', 'artist_id')
    op.drop_table('artist')
    ### end Alembic commands ###
