"""empty message

Revision ID: 2d179032e1b
Revises: 37f14ce6466
Create Date: 2015-08-26 09:43:08.411193

"""

# revision identifiers, used by Alembic.
revision = '2d179032e1b'
down_revision = '37f14ce6466'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('total_discs', sa.Integer(), server_default='1', nullable=True))
    op.add_column('album', sa.Column('total_tracks', sa.Integer(), nullable=True))
    op.drop_column('album', 'disc_total')
    op.drop_column('album', 'size')
    op.add_column('song', sa.Column('track_number', sa.Integer(), nullable=True))
    op.drop_column('song', 'number')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('song', 'track_number')
    op.add_column('album', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('album', sa.Column('disc_total', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.drop_column('album', 'total_tracks')
    op.drop_column('album', 'total_discs')
    ### end Alembic commands ###
