"""empty message

Revision ID: 37f14ce6466
Revises: 5c3ade0283
Create Date: 2015-08-26 09:30:37.076398

"""

# revision identifiers, used by Alembic.
revision = '37f14ce6466'
down_revision = '5c3ade0283'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('disc_total', sa.Integer(), server_default='1', nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'disc_total')
    ### end Alembic commands ###
