"""empty message

Revision ID: 3aa01600e8e
Revises: 26044757012
Create Date: 2015-08-24 16:03:19.863304

"""

# revision identifiers, used by Alembic.
revision = '3aa01600e8e'
down_revision = '26044757012'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ## commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'album',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('size', sa.Integer(), nullable=True),
        sa.Column('year', sa.Integer(), nullable=True),
        sa.Column('artist_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'artist', ['name'])
    op.add_column('song', sa.Column('album_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'song', 'album', ['album_id'], ['id'])
    # ## end Alembic commands ###


def downgrade():
    # ## commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'song', type_='foreignkey')
    op.drop_column('song', 'album_id')
    op.drop_constraint(None, 'artist', type_='unique')
    op.drop_table('album')
    # ## end Alembic commands ###
