"""empty message

Revision ID: 40efa86c6b1
Revises: 2d179032e1b
Create Date: 2015-09-01 10:33:43.424932

"""

# revision identifiers, used by Alembic.
revision = '40efa86c6b1'
down_revision = '2d179032e1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('count_played', sa.Integer(), nullable=True))
    op.add_column('album', sa.Column('count_rated', sa.Integer(), nullable=True))
    op.add_column('album', sa.Column('count_songs', sa.Integer(), nullable=True))
    op.add_column('album', sa.Column('played_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('album', sa.Column('rated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('album', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('artist', sa.Column('count_played', sa.Integer(), nullable=True))
    op.add_column('artist', sa.Column('count_rated', sa.Integer(), nullable=True))
    op.add_column('artist', sa.Column('count_songs', sa.Integer(), nullable=True))
    op.add_column('artist', sa.Column('played_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('artist', sa.Column('rated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('artist', sa.Column('rating', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'rating')
    op.drop_column('artist', 'rated_at')
    op.drop_column('artist', 'played_at')
    op.drop_column('artist', 'count_songs')
    op.drop_column('artist', 'count_rated')
    op.drop_column('artist', 'count_played')
    op.drop_column('album', 'rating')
    op.drop_column('album', 'rated_at')
    op.drop_column('album', 'played_at')
    op.drop_column('album', 'count_songs')
    op.drop_column('album', 'count_rated')
    op.drop_column('album', 'count_played')
    ### end Alembic commands ###
