"""empty message

Revision ID: 47efab2b273
Revises: 2d179032e1b
Create Date: 2015-08-28 16:00:35.140362

"""

# revision identifiers, used by Alembic.
revision = '47efab2b273'
down_revision = '2d179032e1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
