"""empty message

Revision ID: 5282da66ae2
Revises: None
Create Date: 2015-08-21 14:33:01.318093

"""

# revision identifiers, used by Alembic.
revision = '5282da66ae2'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'count_albums')
    op.drop_column('artists', 'count_songs')
    op.drop_column('artists', 'played_at')
    op.drop_column('artists', 'count_played')
    op.add_column('song', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'song', 'artists', ['artist_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'song', type_='foreignkey')
    op.drop_column('song', 'artist_id')
    op.add_column('artists', sa.Column('count_played', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('played_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('count_songs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('count_albums', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
