"""empty message

Revision ID: 573027b82ae
Revises: 4990b498d43
Create Date: 2015-09-11 10:23:51.966167

"""

# revision identifiers, used by Alembic.
revision = '573027b82ae'
down_revision = '4990b498d43'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('song', 'rating',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('song', 'rating',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    ### end Alembic commands ###
