"""empty message

Revision ID: 5c3ade0283
Revises: 1d4a5706ee0
Create Date: 2015-08-26 08:25:59.154859

"""

# revision identifiers, used by Alembic.
revision = '5c3ade0283'
down_revision = '1d4a5706ee0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('disc_number', sa.Integer(), server_default='1', nullable=True))
    op.drop_constraint('uq_album_name_artist', 'album', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_album_name_artist', 'album', ['artist_id', 'name'])
    op.drop_column('album', 'disc_number')
    ### end Alembic commands ###
